INSERT INTO agent (ime, prezime, jmbg, adresa, telefon, korisnicko_ime, sifra, email) VALUES ('Milos', 'Ratkovic', '0404993782851', 'Vojvode Stepe 321', '+381653731577', 'Milos', 'samsung4', 'dowsha032@gmail.com');
INSERT INTO tip_nekretnine (tip) VALUES ('Kuca');
INSERT INTO tip_nekretnine (tip) VALUES ('Stan');
INSERT INTO tip_nekretnine (tip) VALUES ('Lokal');
INSERT INTO tip_nekretnine (tip) VALUES ('Garaza');
INSERT INTO opstina (naziv) VALUES ('Barajevo');
INSERT INTO opstina (naziv) VALUES ('Vozdovac');
INSERT INTO opstina (naziv) VALUES ('Vracar');
INSERT INTO opstina (naziv) VALUES ('Grocka');
INSERT INTO opstina (naziv) VALUES ('Zvezdara');
INSERT INTO opstina (naziv) VALUES ('Zemun');
INSERT INTO opstina (naziv) VALUES ('Lazarevac');
INSERT INTO opstina (naziv) VALUES ('Mladenovac');
INSERT INTO opstina (naziv) VALUES ('Novi Beograd');
INSERT INTO opstina (naziv) VALUES ('Obrenovac');
INSERT INTO opstina (naziv) VALUES ('Rakovica');
INSERT INTO opstina (naziv) VALUES ('Savski Venac');
INSERT INTO opstina (naziv) VALUES ('Sopot');
INSERT INTO opstina (naziv) VALUES ('Stari Grad');
INSERT INTO opstina (naziv) VALUES ('Surcin');
INSERT INTO opstina (naziv) VALUES ('Cukarica');
INSERT INTO opstina (naziv) VALUES ('Palilula');